### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by briteming** [zu1k/shorturl#1]
hi。
https://github.com/zu1k/shorturl/blob/master/go.mod里的第一行shorturl 应该改为github.com/zu1k/shorturl ，否则
运行go install github.com/zu1k/shorturl@latest会提示：
go: downloading github.com/zu1k/shorturl v0.0.0-20200210150740-00f7ccfe8468
go: github.com/zu1k/shorturl@latest: github.com/zu1k/shorturl@v0.0.0-20200210150740-00f7ccfe8468: parsing go.mod:
	module declares its path as: shorturl
	        but was required as: github.com/zu1k/shorturl

另外，我运行shorturl，什么输出都没有。怎么使用它呢？
root@racknerd-7b97d8:~# shorturl -h

^Croot@racknerd-7b97d8:~# shorturl --help

^Croot@racknerd-7b97d8:~# shorturl

**Comment by zu1k** [comment]
It is NOT for use.

DO NOT USE!
